#server:
# port: 9001
#  
#spring:
#  application: 
#    name: Discount-Service
#    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8001/eureka/
#  instance:
#    hostname: localhost
#    